### ISSUE TITLE
Stress Test Number of Clients/Requests Sent at Same Time

### ISSUE THREAD

**Issue by nElder03** [ChapmanCPSC/SE-498_01#111]
## Description
```
As a client,
I can hit the backend with 50 clients at the same time.
```

## Acceptance Criteria
1. Documentation or data showing 50 clients hitting within 30 seconds of another.

**Comment by lancefluger** [comment]
I'm reassigning this issue to Nathaniel

**Comment by nElder03** [comment]
https://files.slack.com/files-pri/T09UMKK9T-FHP9C9YV8/screen_shot_2019-04-18_at_10.27.00_am.png
