### ISSUE TITLE
Login Using Social Networks

### ISSUE THREAD

**Issue by nElder03** [ChapmanCPSC/SE-498_01#117]
## Description
```
As a canvas manager, I can login to the canvassing admin page using my Google login.

If I am unable to use Google Login to access the admin page, then prompt me to create a custom login/password.
```

## Acceptance Criteria
1.  When accessing canvas manager page, present with login info--only after logging in can I see the admin page.
2. Create a form of sorts that allows user to create a custom login/password (in the event their Google login doesn't exist or doesn't work).

**Comment by mchogan** [comment]
Consider an auth middleware that allows sign in with multiple providers like Auth0, https://auth0.com/docs/identityproviders

**Comment by mchogan** [comment]
This ruby gem may help...
https://github.com/omniauth/omniauth/blob/dc44c54d80ca0b49d1f63bbbf21165a7515fd41d/README.markdown
