### ISSUE TITLE
Implement RESTful backend service to expose pg dataset (JSON)

### ISSUE THREAD

**Issue by lancefluger** [ChapmanCPSC/SE-498_01#12]
## Description
As a **developer**,
I can **get and set voter data using a REST API**,
so that **I can populate the front-end side**.

## Acceptance Criteria
- Front end team is able to retrieve a json object with 10 names using a GET request
- #13 is accepted

## Tasks
- Setup REST API on rails app
- Setup API Endpoints

**Comment by xaviablaza** [comment]
Tentative design: https://github.com/ChapmanCPSC/SE-498_01/wiki/API-Docs
