### ISSUE TITLE
Add Note Screen

### ISSUE THREAD

**Issue by nElder03** [ChapmanCPSC/SE-498_01#122]
## Description
```
As a canvasser,
I can add notes to a profile regardless of whether or not I visited the house noted in the profile.

I can save these notes to the backend DB, and I can see previously written notes.
```

## Acceptance Criteria
1. I am able to create notes for a particular profile.
2. I am able to view, save, and update these notes.

**Comment by mchogan** [comment]
Check out Rails’ built in Action Text feature: https://edgeguides.rubyonrails.org/action_text_overview.html
