### ISSUE TITLE
Add Past Voting Score to User Profile

### ISSUE THREAD

**Issue by nElder03** [ChapmanCPSC/SE-498_01#124]
## Description
```
As a canvasser,
I can see how many times the person has previously voted.
```

## Acceptance Criteria
1.  Should show a score in the top-right corner of how many times the person has voted previously.

**Comment by mchogan** [comment]
If there is data for both the number of times a person could have voted and the number of times a person did vote, show both.

Some ideas...

If a person has been eligible for 7 elections and voted 4 times the score might be shown as: 4/7

If a person didn’t vote, then voted, then missed an election, then voted three times, the missed an election, the score might be shown as: 🤐🙂🤐🙂🙂🙂🤐 or✖️✔️✖️✔️✔️✔️✖️

**Comment by mchogan** [comment]
Info on Font Awesome https://fontawesome.com/start
