### ISSUE TITLE
Add ability to set note on backend

### ISSUE THREAD

**Issue by lancefluger** [ChapmanCPSC/SE-498_01#133]
## Description
```
On admin page provide a textbox to add default notes that canvasser see when canvassing a house
```

## Acceptance Criteria
Canvas manager can see textbox on admin page, edit default note and save
Canvaser sees default note set when canvassing a new house

## Tasks
- Create migration that adds note to voter `rails g migration AddNoteToVoter note:string`
- Create global variable `note` in `config/app.yml` which defines the default note
- Add textbox to admin dashboard with button that updates the default note
- Add graphql route that gives the note for the user. If empty, then return the default note
- Add graphql route that updates the note given the user
- Add test to check if the voter note is updated

**Comment by mchogan** [comment]
Might be another good use of Rails Action Text

**Comment by mchogan** [comment]
Given a Canvasser has accepted a Voter to visit
When the Canvasser is on the Note screen
Then the Prompt should appear above the Note entry field to remind the Canvasser what to ask about
