### ISSUE TITLE
Test bad connection; losing connection

### ISSUE THREAD

**Issue by lancefluger** [ChapmanCPSC/SE-498_01#134]
## Description
```
Test what happens to app when connection is poor or connection is lost
```

## Acceptance Criteria
Test report showing screenshots of app when connection is poor or connection is lost; create bug reports for any issues found

**Comment by nElder03** [comment]
Results image: https://files.slack.com/files-pri/T09UMKK9T-FJ5BPPW20/screen_shot_2019-04-24_at_7.54.25_pm.png

**Comment by nElder03** [comment]
https://github.com/ChapmanCPSC/SE-498_01/issues/163
