### ISSUE TITLE
Update note to support having both canvas manager note remain and individual note

### ISSUE THREAD

**Issue by lancefluger** [ChapmanCPSC/SE-498_01#174]
## Description
```
As a canvasser,
I want to be able to see the original note on top and place my individual notes below.
```

## Acceptance Criteria
1. See canvas manager note on top and individual note below.

![FullSizeRender](https://user-images.githubusercontent.com/2496120/56756764-5bae4f80-6747-11e9-80c5-0c16a3ce0358.jpeg)

**Comment by lancefluger** [comment]
@xaviablaza , @lavin105  - What I'm thinking is we may need two columns. One column for the Canvas Manager note and one column for the Canvaser note.  On the client side they can see both (see screenshot) on the Manager export they just see the individual notes or a concatenation.

**Comment by lavin105** [comment]
Can they edit the default canvas manager note from the client side?

**Comment by lancefluger** [comment]
Not editable by canvasser, should be editable for campaign manager
