### ISSUE TITLE
Save Documentation Into Github Project So Can be Used for Future Class

### ISSUE THREAD

**Issue by lancefluger** [ChapmanCPSC/SE-498_01#200]
## Description
```
Save notes/documents/architectural diagrams to GitHub under /docs folder.
```

## Acceptance Criteria
1. Can see documents saved under /docs folder.

**Comment by lancefluger** [comment]
@andrewdieken  - Can you start saving your docs to the github project ?

**Comment by xaviablaza** [comment]
@andrewdieken Please add documentation to the [project wiki](https://github.com/ChapmanCPSC/SE-498_01/wiki).
