### ISSUE TITLE
Update DB on GCP with voters.csv

### ISSUE THREAD

**Issue by andrewdieken** [ChapmanCPSC/SE-498_01#46]
## Description
```
As a user,
I can access voter info through the staging/production site,
so that I can interact with the app with real data.
```

## Acceptance Criteria
List down acceptance criteria that the product owner would have to check.
- se498-01 project DB on GCP has all voter info from voters.csv

**Comment by xaviablaza** [comment]
@andrewdieken: I was just looking at the dataset and in row 134089 the voters last name is `BolaÒos` so I'm assuming `Ò` is not being recognized as a character.

We forced the encoding to `UTF-8` to seed the records properly in the database, and can do a `.encode("ISO-8859-1")` to get the original `BolaÒos` string.

The API will always give out UTF-8 strings and it will be the responsibility of the react-app to consume these and encode them on their end.
